(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("ALU_op" "input alu_op")
 ("InData" "input logic [7:0]")
 ("OutData" "output logic [7:0]")
 ("FlagZ" "output logic")
 ("FlagC" "output logic")
 ("FlagN" "output logic")
 ("FlagE" "output logic")
 ("ASCII_BINARY_0" "local_parameter_declaration")
 ("ASCII_BINARY_9" "local_parameter_declaration")
 ("InA" "logic [7:0]")
 ("InB" "logic [7:0]")
 ("InAcc" "logic [7:0]")
 ("InIndex" "logic [7:0]")
 ("InZ" "logic")
 ("InC" "logic")
 ("InN" "logic")
 ("InE" "logic")
 ("EnA" "logic")
 ("EnB" "logic")
 ("EnAcc" "logic")
 ("EnIndex" "logic")
 ("EnZ" "logic")
 ("EnC" "logic")
 ("EnN" "logic")
 ("EnE" "logic")
 ("OutA" "logic [7:0]")
 ("OutB" "logic [7:0]")
 ("OutAcc" "logic [7:0]")
 ("OutIndex" "logic [7:0]")
 ("alu" "module_declaration"))
