(("AxiIdWidth" "parameter_declaration")
 ("AtopSupport" "parameter_declaration")
 ("aw_chan_t" "parameter_declaration")
 ("w_chan_t" "parameter_declaration")
 ("b_chan_t" "parameter_declaration")
 ("ar_chan_t" "parameter_declaration")
 ("r_chan_t" "parameter_declaration")
 ("axi_req_t" "parameter_declaration")
 ("axi_resp_t" "parameter_declaration")
 ("NoMstPorts" "parameter_declaration")
 ("MaxTrans" "parameter_declaration")
 ("AxiLookBits" "parameter_declaration")
 ("UniqueIds" "parameter_declaration")
 ("SpillAw" "parameter_declaration")
 ("SpillW" "parameter_declaration")
 ("SpillB" "parameter_declaration")
 ("SpillAr" "parameter_declaration")
 ("SpillR" "parameter_declaration")
 ("SelectWidth" "parameter_declaration")
 ("select_t" "parameter_declaration")
 ("clk_i" "input  logic")
 ("rst_ni" "input  logic")
 ("test_i" "input  logic")
 ("slv_req_i" "input  axi_req_t")
 ("slv_aw_select_i" "input  select_t")
 ("slv_ar_select_i" "input  select_t")
 ("slv_resp_o" "output axi_resp_t")
 ("mst_reqs_o" "output axi_req_t    [NoMstPorts-1:0]")
 ("mst_resps_i" "input  axi_resp_t   [NoMstPorts-1:0]")
 ("IdCounterWidth" "local_parameter_declaration")
 ("id_cnt_t" "logic [IdCounterWidth-1:0]")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("slv_aw_chan" "aw_chan_t")
 ("slv_aw_select" "select_t")
 ("slv_aw_valid" "logic")
 ("slv_aw_valid_chan" "logic")
 ("slv_aw_valid_sel" "logic")
 ("slv_aw_ready" "logic")
 ("slv_aw_ready_chan" "logic")
 ("slv_aw_ready_sel" "logic")
 ("lookup_aw_select" "select_t")
 ("aw_select_occupied" "logic")
 ("aw_id_cnt_full" "logic")
 ("atop_inject" "logic")
 ("w_select" "select_t")
 ("w_select_q" "select_t")
 ("w_select_valid" "logic")
 ("w_open" "id_cnt_t")
 ("w_cnt_up" "logic")
 ("w_cnt_down" "logic")
 ("lock_aw_valid_d" "logic")
 ("lock_aw_valid_q" "logic")
 ("load_aw_lock" "logic")
 ("aw_valid" "logic")
 ("aw_ready" "logic")
 ("slv_w_chan" "w_chan_t")
 ("slv_w_valid" "logic")
 ("slv_w_ready" "logic")
 ("mst_b_chans" "b_chan_t [NoMstPorts-1:0]")
 ("mst_b_valids" "logic    [NoMstPorts-1:0]")
 ("mst_b_readies" "logic    [NoMstPorts-1:0]")
 ("slv_b_chan" "b_chan_t")
 ("slv_b_valid" "logic")
 ("slv_b_ready" "logic")
 ("slv_ar_valid" "logic")
 ("ar_valid_chan" "logic")
 ("ar_valid_sel" "logic")
 ("slv_ar_ready" "logic")
 ("slv_ar_ready_chan" "logic")
 ("slv_ar_ready_sel" "logic")
 ("lookup_ar_select" "select_t")
 ("ar_select_occupied" "logic")
 ("ar_id_cnt_full" "logic")
 ("ar_push" "logic")
 ("lock_ar_valid_d" "logic")
 ("lock_ar_valid_q" "logic")
 ("load_ar_lock" "logic")
 ("ar_valid" "logic")
 ("ar_ready" "logic")
 ("mst_r_chans" "r_chan_t [NoMstPorts-1:0]")
 ("mst_r_valids" "logic    [NoMstPorts-1:0]")
 ("mst_r_readies" "logic    [NoMstPorts-1:0]")
 ("slv_r_chan" "r_chan_t")
 ("slv_r_valid" "logic")
 ("slv_r_ready" "logic")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("axi_demux_id_counters" "module_instantiation")
 ("counter" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("rr_arb_tree" "module_instantiation")
 ("slv_ar_chan" "ar_chan_t")
 ("slv_ar_select" "select_t")
 ("spill_register" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("axi_demux_id_counters" "module_instantiation")
 ("spill_register" "module_instantiation")
 ("rr_arb_tree" "module_instantiation")
 ("axi_demux" "module_declaration")
 ("AxiIdBits" "parameter_declaration")
 ("CounterWidth" "parameter_declaration")
 ("mst_port_select_t" "parameter_declaration")
 ("clk_i" "input")
 ("rst_ni" "input")
 ("lookup_axi_id_i" "input  logic [AxiIdBits-1:0]")
 ("lookup_mst_select_o" "output mst_port_select_t")
 ("lookup_mst_select_occupied_o" "output logic")
 ("full_o" "output logic")
 ("push_axi_id_i" "input  logic [AxiIdBits-1:0]")
 ("push_mst_select_i" "input  mst_port_select_t")
 ("push_i" "input  logic")
 ("inject_axi_id_i" "input  logic [AxiIdBits-1:0]")
 ("inject_i" "input  logic")
 ("pop_axi_id_i" "input  logic [AxiIdBits-1:0]")
 ("pop_i" "input  logic")
 ("NoCounters" "local_parameter_declaration")
 ("cnt_t" "logic [CounterWidth-1:0]")
 ("mst_select_q" "mst_port_select_t [NoCounters-1:0]")
 ("push_en" "logic [NoCounters-1:0]")
 ("inject_en" "logic [NoCounters-1:0]")
 ("pop_en" "logic [NoCounters-1:0]")
 ("occupied" "logic [NoCounters-1:0]")
 ("cnt_full" "logic [NoCounters-1:0]")
 ("cnt_en" "logic")
 ("cnt_down" "logic")
 ("overflow" "logic")
 ("cnt_delta" "cnt_t")
 ("in_flight" "cnt_t")
 ("delta_counter" "module_instantiation")
 ("axi_demux_id_counters" "module_declaration")
 ("AXI_ID_WIDTH" "parameter_declaration")
 ("ATOP_SUPPORT" "parameter_declaration")
 ("AXI_ADDR_WIDTH" "parameter_declaration")
 ("AXI_DATA_WIDTH" "parameter_declaration")
 ("AXI_USER_WIDTH" "parameter_declaration")
 ("NO_MST_PORTS" "parameter_declaration")
 ("MAX_TRANS" "parameter_declaration")
 ("AXI_LOOK_BITS" "parameter_declaration")
 ("UNIQUE_IDS" "parameter_declaration")
 ("SPILL_AW" "parameter_declaration")
 ("SPILL_W" "parameter_declaration")
 ("SPILL_B" "parameter_declaration")
 ("SPILL_AR" "parameter_declaration")
 ("SPILL_R" "parameter_declaration")
 ("SELECT_WIDTH" "parameter_declaration")
 ("select_t" "parameter_declaration")
 ("clk_i" "input  logic")
 ("rst_ni" "input  logic")
 ("test_i" "input  logic")
 ("slv_aw_select_i" "input  select_t")
 ("slv_ar_select_i" "input  select_t")
 ("slv" "AXI_BUS.Slave")
 ("mst" "AXI_BUS.Master")
 ("id_t" "logic [AXI_ID_WIDTH-1:0]")
 ("addr_t" "logic [AXI_ADDR_WIDTH-1:0]")
 ("data_t" "logic [AXI_DATA_WIDTH-1:0]")
 ("strb_t" "logic [AXI_DATA_WIDTH/8-1:0]")
 ("user_t" "logic [AXI_USER_WIDTH-1:0]")
 ("slv_req" "axi_req_t")
 ("slv_resp" "axi_resp_t")
 ("mst_req" "axi_req_t  [NO_MST_PORTS-1:0]")
 ("mst_resp" "axi_resp_t [NO_MST_PORTS-1:0]")
 ("axi_demux" "module_instantiation")
 ("axi_demux_intf" "module_declaration"))
