(("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("axi" "virtual AXI_LITE_DV #(\n      .AXI_ADDR_WIDTH(AW),\n      .AXI_DATA_WIDTH(DW)\n    )")
 ("axi" "virtual AXI_LITE_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW)\n      )")
 ("new" "class_constructor_declaration")
 ("reset_master" "function_body_declaration")
 ("reset_slave" "function_body_declaration")
 ("cycle_start" "task_body_declaration")
 ("cycle_end" "task_body_declaration")
 ("addr" "input logic [AW-1:0]")
 ("prot" "input prot_t")
 ("send_aw" "task_body_declaration")
 ("data" "input logic [DW-1:0]")
 ("strb" "input logic [DW/8-1:0]")
 ("send_w" "task_body_declaration")
 ("resp" "input axi_pkg::resp_t")
 ("send_b" "task_body_declaration")
 ("addr" "input logic [AW-1:0]")
 ("prot" "input prot_t")
 ("send_ar" "task_body_declaration")
 ("data" "input logic [DW-1:0]")
 ("resp" "input axi_pkg::resp_t")
 ("send_r" "task_body_declaration")
 ("addr" "output [AW-1:0]")
 ("prot" "output prot_t")
 ("recv_aw" "task_body_declaration")
 ("data" "output [DW-1:0]")
 ("strb" "output [DW/8-1:0]")
 ("recv_w" "task_body_declaration")
 ("resp" "output axi_pkg::resp_t")
 ("recv_b" "task_body_declaration")
 ("addr" "output [AW-1:0]")
 ("prot" "output prot_t")
 ("recv_ar" "task_body_declaration")
 ("data" "output [DW-1:0]")
 ("resp" "output axi_pkg::resp_t")
 ("recv_r" "task_body_declaration")
 ("axi_lite_driver" "class_declaration")
 ("AW" "parameter_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("ax_id" "rand logic [IW-1:0]")
 ("ax_addr" "rand logic [AW-1:0]")
 ("ax_len" "logic [7:0]")
 ("ax_size" "logic [2:0]")
 ("ax_burst" "logic [1:0]")
 ("ax_lock" "logic")
 ("ax_cache" "logic [3:0]")
 ("ax_prot" "logic [2:0]")
 ("ax_qos" "rand logic [3:0]")
 ("ax_region" "logic [3:0]")
 ("ax_atop" "logic [5:0]")
 ("ax_user" "rand logic [UW-1:0]")
 ("axi_ax_beat" "class_declaration")
 ("DW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("w_data" "rand logic [DW-1:0]")
 ("w_strb" "rand logic [DW/8-1:0]")
 ("w_last" "logic")
 ("w_user" "rand logic [UW-1:0]")
 ("axi_w_beat" "class_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("b_id" "rand logic [IW-1:0]")
 ("b_resp" "axi_pkg::resp_t")
 ("b_user" "rand logic [UW-1:0]")
 ("axi_b_beat" "class_declaration")
 ("DW" "parameter_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("r_id" "rand logic [IW-1:0]")
 ("r_data" "rand logic [DW-1:0]")
 ("r_resp" "axi_pkg::resp_t")
 ("r_last" "logic")
 ("r_user" "rand logic [UW-1:0]")
 ("axi_r_beat" "class_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("axi" "virtual AXI_BUS_DV #(\n      .AXI_ADDR_WIDTH(AW),\n      .AXI_DATA_WIDTH(DW),\n      .AXI_ID_WIDTH(IW),\n      .AXI_USER_WIDTH(UW)\n    )")
 ("ax_beat_t" "axi_ax_beat #(.AW(AW), .IW(IW), .UW(UW))")
 ("w_beat_t" "axi_w_beat  #(.DW(DW), .UW(UW))")
 ("b_beat_t" "axi_b_beat  #(.IW(IW), .UW(UW))")
 ("r_beat_t" "axi_r_beat  #(.DW(DW), .IW(IW), .UW(UW))")
 ("axi" "virtual AXI_BUS_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW),\n        .AXI_ID_WIDTH(IW),\n        .AXI_USER_WIDTH(UW)\n      )")
 ("new" "class_constructor_declaration")
 ("reset_master" "function_body_declaration")
 ("reset_slave" "function_body_declaration")
 ("cycle_start" "task_body_declaration")
 ("cycle_end" "task_body_declaration")
 ("beat" "input ax_beat_t")
 ("send_aw" "task_body_declaration")
 ("beat" "input w_beat_t")
 ("send_w" "task_body_declaration")
 ("beat" "input b_beat_t")
 ("send_b" "task_body_declaration")
 ("beat" "input ax_beat_t")
 ("send_ar" "task_body_declaration")
 ("beat" "input r_beat_t")
 ("send_r" "task_body_declaration")
 ("beat" "output ax_beat_t")
 ("recv_aw" "task_body_declaration")
 ("beat" "output w_beat_t")
 ("recv_w" "task_body_declaration")
 ("beat" "output b_beat_t")
 ("recv_b" "task_body_declaration")
 ("beat" "output ax_beat_t")
 ("recv_ar" "task_body_declaration")
 ("beat" "output r_beat_t")
 ("recv_r" "task_body_declaration")
 ("beat" "output ax_beat_t")
 ("mon_aw" "task_body_declaration")
 ("beat" "output w_beat_t")
 ("mon_w" "task_body_declaration")
 ("beat" "output b_beat_t")
 ("mon_b" "task_body_declaration")
 ("beat" "output ax_beat_t")
 ("mon_ar" "task_body_declaration")
 ("beat" "output r_beat_t")
 ("mon_r" "task_body_declaration")
 ("axi_driver" "class_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("MAX_READ_TXNS" "parameter_declaration")
 ("MAX_WRITE_TXNS" "parameter_declaration")
 ("AX_MIN_WAIT_CYCLES" "parameter_declaration")
 ("AX_MAX_WAIT_CYCLES" "parameter_declaration")
 ("W_MIN_WAIT_CYCLES" "parameter_declaration")
 ("W_MAX_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MIN_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MAX_WAIT_CYCLES" "parameter_declaration")
 ("AXI_MAX_BURST_LEN" "parameter_declaration")
 ("TRAFFIC_SHAPING" "parameter_declaration")
 ("AXI_EXCLS" "parameter_declaration")
 ("AXI_ATOPS" "parameter_declaration")
 ("AXI_BURST_FIXED" "parameter_declaration")
 ("AXI_BURST_INCR" "parameter_declaration")
 ("AXI_BURST_WRAP" "parameter_declaration")
 ("UNIQUE_IDS" "parameter_declaration")
 ("AXI_STRB_WIDTH" "parameter_declaration")
 ("N_AXI_IDS" "parameter_declaration")
 ("axi_driver_t" "axi_driver #(\n      .AW(AW), .DW(DW), .IW(IW), .UW(UW), .TA(TA), .TT(TT)\n    )")
 ("addr_t" "logic [AW-1:0]")
 ("burst_t" "axi_pkg::burst_t")
 ("cache_t" "axi_pkg::cache_t")
 ("data_t" "logic [DW-1:0]")
 ("id_t" "logic [IW-1:0]")
 ("len_t" "axi_pkg::len_t")
 ("size_t" "axi_pkg::size_t")
 ("user_t" "logic [UW-1:0]")
 ("mem_type_t" "axi_pkg::mem_type_t")
 ("ax_beat_t" "axi_driver_t::ax_beat_t")
 ("b_beat_t" "axi_driver_t::b_beat_t")
 ("r_beat_t" "axi_driver_t::r_beat_t")
 ("w_beat_t" "axi_driver_t::w_beat_t")
 ("PFN_MASK" "static addr_t")
 ("drv" "axi_driver_t")
 ("r_flight_cnt" "int unsigned / [N_AXI_IDS-1:0]")
 ("w_flight_cnt" "int unsigned / [N_AXI_IDS-1:0]")
 ("tot_r_flight_cnt" "int unsigned")
 ("tot_w_flight_cnt" "int unsigned")
 ("atop_resp_b" "logic [N_AXI_IDS-1:0]")
 ("atop_resp_r" "logic [N_AXI_IDS-1:0]")
 ("max_len" "len_t")
 ("allowed_bursts" "burst_t / [$]")
 ("cnt_sem" "semaphore")
 ("aw_queue" "ax_beat_t / [$]")
 ("w_queue" "ax_beat_t / [$]")
 ("excl_queue" "ax_beat_t / [$]")
 ("addr_begin" "addr_t")
 ("addr_end" "addr_t")
 ("mem_type" "mem_type_t")
 ("mem_region_t" "struct packed {\n      addr_t     addr_begin;\n      addr_t     addr_end;\n      mem_type_t mem_type;\n    }")
 ("mem_map" "mem_region_t / [$]")
 ("len" "int unsigned")
 ("cprob" "int unsigned")
 ("traffic_shape" "struct packed {\n      int unsigned len  ;\n      int unsigned cprob;\n    } / [$]")
 ("max_cprob" "int unsigned")
 ("axi" "virtual AXI_BUS_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW),\n        .AXI_ID_WIDTH(IW),\n        .AXI_USER_WIDTH(UW)\n      )")
 ("new" "class_constructor_declaration")
 ("reset" "function_body_declaration")
 ("addr_begin" "input addr_t")
 ("addr_end" "input addr_t")
 ("mem_type" "input mem_type_t")
 ("add_memory_region" "function_body_declaration")
 ("len" "input int unsigned")
 ("freq" "input int unsigned")
 ("add_traffic_shaping" "function_body_declaration")
 ("is_read" "input logic")
 ("rand_success" "automatic logic")
 ("ax_beat" "automatic ax_beat_t")
 ("addr" "automatic addr_t")
 ("burst" "automatic burst_t")
 ("cache" "automatic cache_t")
 ("id" "automatic id_t")
 ("qos" "automatic qos_t")
 ("len" "automatic len_t")
 ("size" "automatic size_t")
 ("mem_region_idx" "automatic int unsigned")
 ("mem_region" "automatic mem_region_t")
 ("cprob" "automatic int")
 ("new_rand_burst" "function_body_declaration")
 ("beat" "inout ax_beat_t")
 ("rand_success" "automatic logic")
 ("bytes" "automatic int unsigned")
 ("log_bytes" "automatic int unsigned")
 ("log_bytes" "automatic int unsigned")
 ("rand_atop_burst" "task_body_declaration")
 ("ar_beat" "inout ax_beat_t")
 ("rand_success" "automatic logic")
 ("n_bytes" "automatic int unsigned")
 ("size" "automatic size_t")
 ("addr_mask" "automatic addr_t")
 ("ul" "static int unsigned")
 ("rand_excl_ar" "function_body_declaration")
 ("min" "input int unsigned")
 ("max" "")
 ("rand_success" "int unsigned")
 ("cycles" "int unsigned")
 ("rand_wait" "task_body_declaration")
 ("is_read" "input bit")
 ("beat" "input ax_beat_t")
 ("id_is_legal" "function_body_declaration")
 ("is_read" "input bit")
 ("beat" "inout ax_beat_t")
 ("rand_success" "automatic logic")
 ("id" "automatic id_t")
 ("legalize_id" "task_body_declaration")
 ("n_reads" "input int")
 ("rand_success" "automatic logic")
 ("id" "automatic id_t")
 ("ar_beat" "automatic ax_beat_t")
 ("send_ars" "task_body_declaration")
 ("ar_done" "ref logic")
 ("aw_done" "")
 ("r_beat" "automatic r_beat_t")
 ("recv_rs" "task_body_declaration")
 ("n_writes" "input int")
 ("rand_success" "automatic logic")
 ("excl" "automatic bit")
 ("aw_beat" "automatic ax_beat_t")
 ("create_aws" "task_body_declaration")
 ("aw_done" "ref logic")
 ("aw_beat" "automatic ax_beat_t")
 ("send_aws" "task_body_declaration")
 ("aw_done" "ref logic")
 ("aw_beat" "automatic ax_beat_t")
 ("addr" "automatic addr_t")
 ("rand_success" "static logic")
 ("w_beat" "automatic w_beat_t")
 ("begin_byte" "automatic int unsigned")
 ("end_byte" "automatic int unsigned")
 ("n_bytes" "automatic int unsigned")
 ("rand_strb" "automatic logic [AXI_STRB_WIDTH-1:0]")
 ("strb_mask" "automatic logic [AXI_STRB_WIDTH-1:0]")
 ("send_ws" "task_body_declaration")
 ("aw_done" "ref logic")
 ("b_beat" "automatic b_beat_t")
 ("recv_bs" "task_body_declaration")
 ("n_reads" "input int")
 ("n_writes" "input int")
 ("ar_done" "automatic logic")
 ("aw_done" "automatic logic")
 ("run" "task_body_declaration")
 ("axi_rand_master" "class_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("IW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("RAND_RESP" "parameter_declaration")
 ("AX_MIN_WAIT_CYCLES" "parameter_declaration")
 ("AX_MAX_WAIT_CYCLES" "parameter_declaration")
 ("R_MIN_WAIT_CYCLES" "parameter_declaration")
 ("R_MAX_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MIN_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MAX_WAIT_CYCLES" "parameter_declaration")
 ("MAPPED" "parameter_declaration")
 ("axi_driver_t" "axi_driver #(\n      .AW(AW), .DW(DW), .IW(IW), .UW(UW), .TA(TA), .TT(TT)\n    )")
 ("rand_ax_beat_queue_t" "rand_id_queue #(\n      .data_t   (axi_driver_t::ax_beat_t),\n      .ID_WIDTH (IW)\n    )")
 ("ax_beat_t" "axi_driver_t::ax_beat_t")
 ("b_beat_t" "axi_driver_t::b_beat_t")
 ("r_beat_t" "axi_driver_t::r_beat_t")
 ("w_beat_t" "axi_driver_t::w_beat_t")
 ("addr_t" "logic [AW-1:0]")
 ("byte_t" "logic [7:0]")
 ("drv" "axi_driver_t")
 ("ar_queue" "rand_ax_beat_queue_t")
 ("aw_queue" "ax_beat_t / [$]")
 ("b_wait_cnt" "int unsigned")
 ("memory_q" "byte_t / [addr_t]")
 ("axi" "virtual AXI_BUS_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW),\n        .AXI_ID_WIDTH(IW),\n        .AXI_USER_WIDTH(UW)\n      )")
 ("new" "class_constructor_declaration")
 ("reset" "function_body_declaration")
 ("min" "input int unsigned")
 ("max" "")
 ("rand_success" "int unsigned")
 ("cycles" "int unsigned")
 ("rand_wait" "task_body_declaration")
 ("ar_beat" "automatic ax_beat_t")
 ("recv_ars" "task_body_declaration")
 ("rand_success" "automatic logic")
 ("ar_beat" "automatic ax_beat_t")
 ("r_beat" "automatic r_beat_t")
 ("byte_addr" "automatic addr_t")
 ("send_rs" "task_body_declaration")
 ("aw_beat" "automatic ax_beat_t")
 ("recv_aws" "task_body_declaration")
 ("aw_beat" "automatic ax_beat_t")
 ("byte_addr" "automatic addr_t")
 ("w_beat" "automatic w_beat_t")
 ("recv_ws" "task_body_declaration")
 ("aw_beat" "automatic ax_beat_t")
 ("b_beat" "automatic b_beat_t")
 ("rand_success" "automatic logic")
 ("send_bs" "task_body_declaration")
 ("run" "task_body_declaration")
 ("axi_rand_slave" "class_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("MIN_ADDR" "parameter_declaration")
 ("MAX_ADDR" "parameter_declaration")
 ("MAX_READ_TXNS" "parameter_declaration")
 ("MAX_WRITE_TXNS" "parameter_declaration")
 ("AX_MIN_WAIT_CYCLES" "parameter_declaration")
 ("AX_MAX_WAIT_CYCLES" "parameter_declaration")
 ("W_MIN_WAIT_CYCLES" "parameter_declaration")
 ("W_MAX_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MIN_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MAX_WAIT_CYCLES" "parameter_declaration")
 ("axi_driver_t" "axi_lite_driver #(\n      .AW(AW), .DW(DW), .TA(TA), .TT(TT)\n    )")
 ("addr_t" "logic [AW-1:0]")
 ("data_t" "logic [DW-1:0]")
 ("strb_t" "logic [DW/8-1:0]")
 ("name" "string")
 ("drv" "axi_driver_t")
 ("aw_queue" "addr_t / [$]")
 ("ar_queue" "addr_t / [$]")
 ("b_queue" "logic / [$]")
 ("w_queue" "logic / [$]")
 ("axi" "virtual AXI_LITE_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW)\n      )")
 ("name" "input string")
 ("new" "class_constructor_declaration")
 ("reset" "function_body_declaration")
 ("min" "input int unsigned")
 ("max" "")
 ("rand_success" "int unsigned")
 ("cycles" "int unsigned")
 ("rand_wait" "task_body_declaration")
 ("n_reads" "input int unsigned")
 ("ar_addr" "automatic addr_t")
 ("ar_prot" "automatic prot_t")
 ("send_ars" "task_body_declaration")
 ("n_reads" "input int unsigned")
 ("ar_addr" "automatic addr_t")
 ("r_data" "automatic data_t")
 ("r_resp" "automatic axi_pkg::resp_t")
 ("recv_rs" "task_body_declaration")
 ("n_writes" "input int unsigned")
 ("aw_addr" "automatic addr_t")
 ("aw_prot" "automatic prot_t")
 ("send_aws" "task_body_declaration")
 ("n_writes" "input int unsigned")
 ("rand_success" "automatic logic")
 ("aw_addr" "automatic addr_t")
 ("w_data" "automatic data_t")
 ("w_strb" "automatic strb_t")
 ("send_ws" "task_body_declaration")
 ("n_writes" "input int unsigned")
 ("go_b" "automatic logic")
 ("b_resp" "automatic axi_pkg::resp_t")
 ("recv_bs" "task_body_declaration")
 ("n_reads" "input int unsigned")
 ("n_writes" "input int unsigned")
 ("run" "task_body_declaration")
 ("w_addr" "input addr_t")
 ("w_prot" "input prot_t")
 ("w_data" "input data_t")
 ("w_strb" "input strb_t")
 ("b_resp" "output axi_pkg::resp_t")
 ("write" "task_body_declaration")
 ("r_addr" "input addr_t")
 ("r_prot" "input prot_t")
 ("r_data" "output data_t")
 ("r_resp" "output axi_pkg::resp_t")
 ("read" "task_body_declaration")
 ("axi_lite_rand_master" "class_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("TA" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("AX_MIN_WAIT_CYCLES" "parameter_declaration")
 ("AX_MAX_WAIT_CYCLES" "parameter_declaration")
 ("R_MIN_WAIT_CYCLES" "parameter_declaration")
 ("R_MAX_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MIN_WAIT_CYCLES" "parameter_declaration")
 ("RESP_MAX_WAIT_CYCLES" "parameter_declaration")
 ("axi_driver_t" "axi_lite_driver #(\n      .AW(AW), .DW(DW), .TA(TA), .TT(TT)\n    )")
 ("addr_t" "logic [AW-1:0]")
 ("data_t" "logic [DW-1:0]")
 ("strb_t" "logic [DW/8-1:0]")
 ("name" "string")
 ("drv" "axi_driver_t")
 ("aw_queue" "addr_t / [$]")
 ("ar_queue" "addr_t / [$]")
 ("b_queue" "logic / [$]")
 ("axi" "virtual AXI_LITE_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW)\n      )")
 ("name" "input string")
 ("new" "class_constructor_declaration")
 ("reset" "function_body_declaration")
 ("min" "input int unsigned")
 ("max" "")
 ("rand_success" "int unsigned")
 ("cycles" "int unsigned")
 ("rand_wait" "task_body_declaration")
 ("ar_addr" "automatic addr_t")
 ("ar_prot" "automatic prot_t")
 ("recv_ars" "task_body_declaration")
 ("rand_success" "automatic logic")
 ("ar_addr" "automatic addr_t")
 ("r_data" "automatic data_t")
 ("send_rs" "task_body_declaration")
 ("aw_addr" "automatic addr_t")
 ("aw_prot" "automatic prot_t")
 ("recv_aws" "task_body_declaration")
 ("w_data" "automatic data_t")
 ("w_strb" "automatic strb_t")
 ("recv_ws" "task_body_declaration")
 ("rand_success" "automatic logic")
 ("go_aw" "automatic addr_t")
 ("go_b" "automatic logic")
 ("b_resp" "automatic axi_pkg::resp_t")
 ("send_bs" "task_body_declaration")
 ("run" "task_body_declaration")
 ("axi_lite_rand_slave" "class_declaration")
 ("IW" "parameter_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("axi_driver_t" "axi_driver #(\n      .AW(AW), .DW(DW), .IW(IW), .UW(UW), .TA(TT), .TT(TT)\n    )")
 ("ax_beat_t" "axi_driver_t::ax_beat_t")
 ("w_beat_t" "axi_driver_t::w_beat_t")
 ("b_beat_t" "axi_driver_t::b_beat_t")
 ("r_beat_t" "axi_driver_t::r_beat_t")
 ("drv" "axi_driver_t")
 ("aw_mbx" "mailbox")
 ("w_mbx" "mailbox")
 ("b_mbx" "mailbox")
 ("ar_mbx" "mailbox")
 ("r_mbx" "mailbox")
 ("axi" "virtual AXI_BUS_DV #(\n        .AXI_ADDR_WIDTH(AW),\n        .AXI_DATA_WIDTH(DW),\n        .AXI_ID_WIDTH(IW),\n        .AXI_USER_WIDTH(UW)\n      )")
 ("new" "class_constructor_declaration")
 ("ax" "automatic ax_beat_t")
 ("w" "automatic w_beat_t")
 ("b" "automatic b_beat_t")
 ("ax" "automatic ax_beat_t")
 ("r" "automatic r_beat_t")
 ("monitor" "task_body_declaration")
 ("axi_monitor" "class_declaration")
 ("IW" "parameter_declaration")
 ("AW" "parameter_declaration")
 ("DW" "parameter_declaration")
 ("UW" "parameter_declaration")
 ("TT" "parameter_declaration")
 ("NUM_CHECKS" "local_parameter_declaration")
 ("BUS_SIZE" "local_parameter_declaration")
 ("check_e" "enum logic [1:0] {\n      ReadCheck  = 2'd0,\n      BRespCheck = 2'd1,\n      RRespCheck = 2'd2\n    }")
 ("byte_t" "logic [7:0]")
 ("axi_id_t" "logic [IW-1:0]")
 ("axi_addr_t" "logic [AW-1:0]")
 ("ax_beat_t" "axi_ax_beat #(.AW(AW), .IW(IW), .UW(UW))")
 ("w_beat_t" "axi_w_beat  #(.DW(DW), .UW(UW))")
 ("b_beat_t" "axi_b_beat  #(.IW(IW), .UW(UW))")
 ("r_beat_t" "axi_r_beat  #(.DW(DW), .IW(IW), .UW(UW))")
 ("axi" "virtual AXI_BUS_DV #(\n      .AXI_ADDR_WIDTH ( AW ),\n      .AXI_DATA_WIDTH ( DW ),\n      .AXI_ID_WIDTH   ( IW ),\n      .AXI_USER_WIDTH ( UW )\n    )")
 ("memory_q" "protected byte_t / [axi_addr_t][$]")
 ("check_en" "protected bit [NUM_CHECKS-1:0]")
 ("aw_sample" "protected ax_beat_t / [$]")
 ("w_sample" "protected w_beat_t / [$]")
 ("b_sample" "protected b_beat_t / [2**IW][$]")
 ("ar_sample" "protected ax_beat_t / [2**IW][$]")
 ("r_sample" "protected r_beat_t / [2**IW][$]")
 ("b_queue" "protected ax_beat_t / [2**IW][$]")
 ("axi" "virtual AXI_BUS_DV #(\n        .AXI_ADDR_WIDTH ( AW ),\n        .AXI_DATA_WIDTH ( DW ),\n        .AXI_ID_WIDTH   ( IW ),\n        .AXI_USER_WIDTH ( UW )\n      )")
 ("new" "class_constructor_declaration")
 ("cycle_start" "task_body_declaration")
 ("cycle_end" "task_body_declaration")
 ("beat_addresses" "axi_addr_t / []")
 ("bus_address" "axi_addr_t")
 ("aw_beat" "ax_beat_t")
 ("w_beat" "w_beat_t")
 ("write_data" "byte_t")
 ("handle_write" "task_body_declaration")
 ("id" "input axi_id_t")
 ("aw_beat" "ax_beat_t")
 ("b_beat" "b_beat_t")
 ("bus_address" "axi_addr_t")
 ("handle_write_resp" "task_body_declaration")
 ("id" "input axi_id_t")
 ("ar_beat" "ax_beat_t")
 ("r_beat" "r_beat_t")
 ("bus_address" "axi_addr_t")
 ("beat_address" "axi_addr_t")
 ("idx_data" "axi_addr_t")
 ("act_data" "byte_t")
 ("exp_data" "byte_t / [$]")
 ("tst_data" "byte_t / [$]")
 ("handle_read" "task_body_declaration")
 ("aw_beat" "ax_beat_t")
 ("mon_aw" "task_body_declaration")
 ("w_beat" "w_beat_t")
 ("mon_w" "task_body_declaration")
 ("b_beat" "b_beat_t")
 ("mon_b" "task_body_declaration")
 ("ar_beat" "ax_beat_t")
 ("mon_ar" "task_body_declaration")
 ("r_beat" "r_beat_t")
 ("mon_r" "task_body_declaration")
 ("j" "int unsigned")
 ("monitor" "task_body_declaration")
 ("enable_read_check" "task_body_declaration")
 ("disable_read_check" "task_body_declaration")
 ("enable_b_resp_check" "task_body_declaration")
 ("disable_b_resp_check" "task_body_declaration")
 ("enable_r_resp_check" "task_body_declaration")
 ("disable_r_resp_check" "task_body_declaration")
 ("enable_all_checks" "task_body_declaration")
 ("disable_all_checks" "task_body_declaration")
 ("reset" "task_body_declaration")
 ("check_addr" "axi_addr_t")
 ("check_data" "byte_t")
 ("check_byte" "task_body_declaration")
 ("clear_addr" "axi_addr_t")
 ("clear_byte" "task_body_declaration")
 ("clear_start_addr" "axi_addr_t")
 ("clear_end_addr" "")
 ("curr_addr" "axi_addr_t")
 ("clear_range" "task_body_declaration")
 ("byte_addr" "input axi_addr_t")
 ("byte_data" "output byte_t")
 ("get_byte" "task_body_declaration")
 ("axi_scoreboard" "class_declaration")
 ("axi_test" "package_declaration")
 ("TestTime" "parameter_declaration")
 ("LoggerName" "parameter_declaration")
 ("aw_chan_t" "parameter_declaration")
 ("w_chan_t" "parameter_declaration")
 ("b_chan_t" "parameter_declaration")
 ("ar_chan_t" "parameter_declaration")
 ("r_chan_t" "parameter_declaration")
 ("clk_i" "input logic")
 ("rst_ni" "input logic")
 ("end_sim_i" "input logic")
 ("aw_chan_i" "input aw_chan_t")
 ("aw_valid_i" "input logic")
 ("aw_ready_i" "input logic")
 ("w_chan_i" "input w_chan_t")
 ("w_valid_i" "input logic")
 ("w_ready_i" "input logic")
 ("b_chan_i" "input b_chan_t")
 ("b_valid_i" "input logic")
 ("b_ready_i" "input logic")
 ("ar_chan_i" "input ar_chan_t")
 ("ar_valid_i" "input logic")
 ("ar_ready_i" "input logic")
 ("r_chan_i" "input r_chan_t")
 ("r_valid_i" "input logic")
 ("r_ready_i" "input logic")
 ("IdWidth" "local_parameter_declaration")
 ("NoIds" "local_parameter_declaration")
 ("aw_queue" "aw_chan_t / [$]")
 ("w_queue" "w_chan_t / [$]")
 ("b_queue" "b_chan_t / [$]")
 ("ar_queues" "aw_chan_t / [NoIds-1:0][$]")
 ("r_queues" "r_chan_t / [NoIds-1:0][$]")
 ("ar_beat" "automatic aw_chan_t")
 ("fd" "automatic int")
 ("log_file" "automatic string")
 ("log_str" "automatic string")
 ("log_name" "automatic string")
 ("log_string" "automatic string")
 ("aw_beat" "automatic aw_chan_t")
 ("w_beat" "automatic w_chan_t")
 ("no_w_beat" "automatic int unsigned")
 ("b_beat" "automatic b_chan_t")
 ("ar_beat" "automatic aw_chan_t")
 ("r_beat" "automatic r_chan_t")
 ("no_r_beat" "automatic int unsigned / [NoIds]")
 ("fd" "automatic int")
 ("axi_chan_logger" "module_declaration"))
