(("BIN_WIDTH" "parameter_declaration")
 ("DEC_DIGITS" "parameter_declaration")
 ("Clk" "input logic")
 ("Rst_n" "input logic")
 ("DataBin" "input logic [BIN_WIDTH-1:0]")
 ("Start" "input logic")
 ("DataBCD" "output logic [DEC_DIGITS*4-1:0]")
 ("Done" "output logic")
 ("state_t" "enum logic [2:0] {\n                 IDLE,\n                 SHIFT,\n                 CHECK_SHIFT_INDEX,\n                 ADD,\n                 CHECK_DIGIT_INDEX,\n                 BCD_DONE\n                 }")
 ("state" "state_t")
 ("bcd_i" "logic [DEC_DIGITS*4-1:0]")
 ("databin_i" "logic [BIN_WIDTH-1:0]")
 ("digit_idx" "logic [DEC_DIGITS-1:0]")
 ("loop_count" "logic [7:0]")
 ("bcd_digit" "logic [3:0]")
 ("bin2bcd" "module_declaration"))
