(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("ROM_Data" "input logic [11:0]")
 ("ROM_Addr" "output logic [11:0]")
 ("RAM_Addr" "output logic [7:0]")
 ("RAM_Cs" "output logic")
 ("RAM_Wen" "output logic")
 ("RAM_Oen" "output logic")
 ("DataOut" "output logic [7:0]")
 ("DataIn" "input logic [7:0]")
 ("DMA_Req" "input logic")
 ("DMA_Ack" "output logic")
 ("DMA_Tx_Start" "output logic")
 ("DMA_Ready" "input logic")
 ("ALU_op" "output alu_op")
 ("ALU_DataOut" "input logic [7:0]")
 ("ALU_DataIn" "output logic [7:0]")
 ("FlagZ" "input logic")
 ("FlagC" "input logic")
 ("FlagN" "input logic")
 ("FlagE" "input logic")
 ("state_t" "enum logic[2:0] {\n                 IDLE,\n                 FETCH,\n                 DECODE,\n                 EXECUTE,\n                 READ_MEM,\n		 WAIT_DMA\n                 }")
 ("state" "state_t")
 ("next_state" "state_t")
 ("pc_ena" "logic")
 ("load_inst" "logic")
 ("load_inst_auxbyte" "logic")
 ("rom_instruction" "logic [11:0]")
 ("rom_aux" "logic [11:0]")
 ("addr" "logic [11:0]")
 ("addr_aux" "logic [11:0]")
 ("alu_data" "logic [7:0]")
 ("decode_type1_inst" "task_body_declaration")
 ("decode_type2_inst" "task_body_declaration")
 ("decode_type3_inst" "task_body_declaration")
 ("decode_type4_inst" "task_body_declaration")
 ("execute_type2_inst" "task_body_declaration")
 ("execute_type3_inst" "task_body_declaration")
 ("cpu" "module_declaration"))
