(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("RX_Data" "input logic [7:0]")
 ("RX_Empty" "input logic")
 ("Data_Read" "output logic")
 ("RX_Full" "input logic")
 ("TX_Data" "output logic [7:0]")
 ("TX_Valid" "output logic")
 ("TX_Ready" "input logic")
 ("Address" "output logic [7:0]")
 ("DataIn" "input logic [7:0]")
 ("DataOut" "output logic [7:0]")
 ("Cs" "output logic")
 ("Wen" "output logic")
 ("Oen" "output logic")
 ("Bus_req" "output logic")
 ("Bus_grant" "input logic")
 ("Dma_Tx_Start" "input logic")
 ("Dma_Tx_Ready" "output logic")
 ("Dma_Idle" "output logic")
 ("Dma_Rx_End" "logic")
 ("Ena_tx" "logic")
 ("Ena_rx" "logic")
 ("Cs_tx" "logic")
 ("Cs_rx" "logic")
 ("Bus_req_tx" "logic")
 ("Bus_req_rx" "logic")
 ("Address_tx" "logic [7:0]")
 ("Address_rx" "logic [7:0]")
 ("dma_tx" "module_instantiation")
 ("dma_rx" "module_instantiation")
 ("dma_arbiter" "module_instantiation")
 ("dma" "module_declaration"))
