(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Ena" "input logic")
 ("Address" "output logic [7:0]")
 ("Databus" "input logic [7:0]")
 ("TX_Ready" "input logic")
 ("TX_Valid" "output logic")
 ("TX_Data" "output logic [7:0]")
 ("Cs" "output logic")
 ("Oen" "output logic")
 ("Bus_req" "output logic")
 ("Bus_grant" "input logic")
 ("Start" "input logic")
 ("Dma_Ready" "output logic")
 ("state_t" "enum logic[1:0] {\n                 IDLE,\n                 BUS_REQUEST,\n                 SEND_MSB,\n                 SEND_LSB\n                 }")
 ("state" "state_t")
 ("next_state" "state_t")
 ("dma_tx" "module_declaration"))
