(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("TX_Start" "input logic")
 ("Dma_Tx_Ready" "input logic")
 ("RX_Pending" "input logic")
 ("Dma_Rx_End" "input logic")
 ("Dma_Idle" "output logic")
 ("Enable_tx" "output logic")
 ("Enable_rx" "output logic")
 ("Address_tx" "input logic [7:0]")
 ("Address_rx" "input logic [7:0]")
 ("Address" "output logic [7:0]")
 ("Cs_tx" "input logic")
 ("Cs_rx" "input logic")
 ("Cs" "output logic")
 ("Bus_req_tx" "input logic")
 ("Bus_req_rx" "input logic")
 ("Bus_req" "output logic")
 ("state_t" "enum logic [1:0] {\n                 IDLE,\n                 TX_ON,\n                 RX_ON\n                 }")
 ("state" "state_t")
 ("dma_arbiter" "module_declaration"))
