(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Ena" "input logic")
 ("Dma_End" "output logic")
 ("Address" "output logic [7:0]")
 ("Databus" "output logic [7:0]")
 ("RX_Data" "input logic [7:0]")
 ("RX_Full" "input logic")
 ("RX_Empty" "input logic")
 ("Data_Read" "output logic")
 ("Cs" "output logic")
 ("Wena" "output logic")
 ("Bus_req" "output logic")
 ("Bus_grant" "input logic")
 ("state_t" "enum logic [3:0] {\n                 IDLE,\n                 BUS_REQUEST,\n                 READ_MSB,\n                 RECEIVE_MSB,\n                 READ_MID,\n                 RECEIVE_MID,\n                 READ_LSB,\n                 RECEIVE_LSB,\n                 DMA_END\n                 }")
 ("state" "state_t")
 ("next_state" "state_t")
 ("dma_rx" "module_declaration"))
