(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Din" "input logic [7:0]")
 ("Wren" "input logic")
 ("Rden" "input logic")
 ("Dout" "input logic [7:0]")
 ("Full" "input logic")
 ("Empty" "input logic")
 ("fifo_generator_0" "module_instantiation")
 ("fifo_wrapper" "module_declaration"))
