(("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rst" "wire")
 ("wr_en" "wire")
 ("NLW_U0_almost_empty_UNCONNECTED" "wire")
 ("NLW_U0_almost_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_underflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_aw_underflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_b_underflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_r_underflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axi_w_underflow_UNCONNECTED" "wire")
 ("NLW_U0_axis_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axis_overflow_UNCONNECTED" "wire")
 ("NLW_U0_axis_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_axis_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_axis_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_axis_underflow_UNCONNECTED" "wire")
 ("NLW_U0_dbiterr_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_arvalid_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_awvalid_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_bready_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_rready_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_wlast_UNCONNECTED" "wire")
 ("NLW_U0_m_axi_wvalid_UNCONNECTED" "wire")
 ("NLW_U0_m_axis_tlast_UNCONNECTED" "wire")
 ("NLW_U0_m_axis_tvalid_UNCONNECTED" "wire")
 ("NLW_U0_overflow_UNCONNECTED" "wire")
 ("NLW_U0_prog_empty_UNCONNECTED" "wire")
 ("NLW_U0_prog_full_UNCONNECTED" "wire")
 ("NLW_U0_rd_rst_busy_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_arready_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_awready_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_bvalid_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_rlast_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_rvalid_UNCONNECTED" "wire")
 ("NLW_U0_s_axi_wready_UNCONNECTED" "wire")
 ("NLW_U0_s_axis_tready_UNCONNECTED" "wire")
 ("NLW_U0_sbiterr_UNCONNECTED" "wire")
 ("NLW_U0_underflow_UNCONNECTED" "wire")
 ("NLW_U0_valid_UNCONNECTED" "wire")
 ("NLW_U0_wr_ack_UNCONNECTED" "wire")
 ("NLW_U0_wr_rst_busy_UNCONNECTED" "wire")
 ("NLW_U0_axi_ar_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_ar_rd_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_ar_wr_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_aw_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_aw_rd_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_aw_wr_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_b_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_b_rd_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_b_wr_data_count_UNCONNECTED" "wire [4:0]")
 ("NLW_U0_axi_r_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axi_r_rd_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axi_r_wr_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axi_w_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axi_w_rd_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axi_w_wr_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axis_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axis_rd_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_axis_wr_data_count_UNCONNECTED" "wire [10:0]")
 ("NLW_U0_data_count_UNCONNECTED" "wire [9:0]")
 ("NLW_U0_m_axi_araddr_UNCONNECTED" "wire [31:0]")
 ("NLW_U0_m_axi_arburst_UNCONNECTED" "wire [1:0]")
 ("NLW_U0_m_axi_arcache_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_arid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_arlen_UNCONNECTED" "wire [7:0]")
 ("NLW_U0_m_axi_arlock_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_arprot_UNCONNECTED" "wire [2:0]")
 ("NLW_U0_m_axi_arqos_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_arregion_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_arsize_UNCONNECTED" "wire [2:0]")
 ("NLW_U0_m_axi_aruser_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_awaddr_UNCONNECTED" "wire [31:0]")
 ("NLW_U0_m_axi_awburst_UNCONNECTED" "wire [1:0]")
 ("NLW_U0_m_axi_awcache_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_awid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_awlen_UNCONNECTED" "wire [7:0]")
 ("NLW_U0_m_axi_awlock_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_awprot_UNCONNECTED" "wire [2:0]")
 ("NLW_U0_m_axi_awqos_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_awregion_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_m_axi_awsize_UNCONNECTED" "wire [2:0]")
 ("NLW_U0_m_axi_awuser_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_wdata_UNCONNECTED" "wire [63:0]")
 ("NLW_U0_m_axi_wid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axi_wstrb_UNCONNECTED" "wire [7:0]")
 ("NLW_U0_m_axi_wuser_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axis_tdata_UNCONNECTED" "wire [7:0]")
 ("NLW_U0_m_axis_tdest_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axis_tid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axis_tkeep_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axis_tstrb_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_m_axis_tuser_UNCONNECTED" "wire [3:0]")
 ("NLW_U0_rd_data_count_UNCONNECTED" "wire [9:0]")
 ("NLW_U0_s_axi_bid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_s_axi_bresp_UNCONNECTED" "wire [1:0]")
 ("NLW_U0_s_axi_buser_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_s_axi_rdata_UNCONNECTED" "wire [63:0]")
 ("NLW_U0_s_axi_rid_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_s_axi_rresp_UNCONNECTED" "wire [1:0]")
 ("NLW_U0_s_axi_ruser_UNCONNECTED" "wire [0:0]")
 ("NLW_U0_wr_data_count_UNCONNECTED" "wire [9:0]")
 ("fifo_generator_0_fifo_generator_v13_2_3" "module_instantiation")
 ("fifo_generator_0" "module_declaration")
 ("clk" "wire")
 ("dbr_as_reg" "wire")
 ("dbr_d1" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rd_rst_i" "wire")
 ("sbr_as_reg" "wire")
 ("sbr_d1" "wire")
 ("wr_en" "wire")
 ("fifo_generator_0_builtin_prim_v6" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("fifo_generator_0_builtin_extdepth_v6" "module_declaration")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 ("p_4_out" "wire")
 ("p_5_out" "wire")
 ("prog_empty_fifo" "wire")
 ("prog_full_fifo" "wire")
 ("rd_en" "wire")
 ("rd_rst_i" "wire")
 ("wr_en" "wire")
 (nil "wire [31:16]")
 (nil "wire [3:2]")
 (nil "wire [11:10]")
 (nil "wire [11:10]")
 ("FIFO18E1" "module_instantiation")
 ("fifo_generator_0_builtin_prim_v6" "module_declaration")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rd_rst_i" "wire")
 ("wr_en" "wire")
 ("fifo_generator_0_builtin_extdepth_v6" "module_instantiation")
 ("fifo_generator_0_builtin_top_v6" "module_declaration")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rst" "wire")
 ("wr_en" "wire")
 ("fifo_generator_0_fifo_generator_v13_2_3_builtin" "module_instantiation")
 ("fifo_generator_0_fifo_generator_top" "module_declaration")
 (nil "wire")
 (nil "wire")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rst" "wire")
 ("wr_en" "wire")
 ("GND" "module_instantiation")
 ("VCC" "module_instantiation")
 ("fifo_generator_0_fifo_generator_v13_2_3_synth" "module_instantiation")
 ("fifo_generator_0_fifo_generator_v13_2_3" "module_declaration")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rd_rst_i" "wire")
 ("rst" "wire")
 ("wr_en" "wire")
 ("fifo_generator_0_reset_builtin" "module_instantiation")
 ("fifo_generator_0_builtin_top_v6" "module_instantiation")
 ("fifo_generator_0_fifo_generator_v13_2_3_builtin" "module_declaration")
 ("clk" "wire")
 ("din" "wire [7:0]")
 ("dout" "wire [7:0]")
 ("empty" "wire")
 ("full" "wire")
 ("rd_en" "wire")
 ("rst" "wire")
 ("wr_en" "wire")
 ("fifo_generator_0_fifo_generator_top" "module_instantiation")
 ("fifo_generator_0_fifo_generator_v13_2_3_synth" "module_declaration")
 ("clk" "wire")
 ("power_on_rd_rst" "wire [5:0]")
 ("power_on_wr_rst" "wire [5:0]")
 ("rd_rst_i" "wire")
 ("rd_rst_reg1" "wire")
 ("rd_rst_reg2" "wire")
 ("rst" "wire")
 (nil "wire")
 (nil "wire")
 (nil "wire")
 ("wr_rst_reg" "wire")
 ("wr_rst_reg1" "wire")
 ("wr_rst_reg2" "wire")
 ("LUT2" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("LUT1" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("FDRE" "module_instantiation")
 ("SRL16E" "module_instantiation")
 ("FDPE" "module_instantiation")
 ("FDPE" "module_instantiation")
 ("LUT2" "module_instantiation")
 ("FDPE" "module_instantiation")
 ("fifo_generator_0_reset_builtin" "module_declaration")
 ("ROC_WIDTH" "parameter_declaration")
 ("TOC_WIDTH" "parameter_declaration")
 ("GSR" "wire")
 ("GTS" "wire")
 ("GWE" "wire")
 ("PRLD" "wire")
 ("p_up_tmp" "tri1")
 ("PLL_LOCKG" "tri (weak1, strong0)")
 ("PROGB_GLBL" "wire")
 ("CCLKO_GLBL" "wire")
 ("FCSBO_GLBL" "wire")
 ("DO_GLBL" "wire [3:0]")
 ("DI_GLBL" "wire [3:0]")
 ("GSR_int" "reg")
 ("GTS_int" "reg")
 ("PRLD_int" "reg")
 ("JTAG_TDO_GLBL" "wire")
 ("JTAG_TCK_GLBL" "wire")
 ("JTAG_TDI_GLBL" "wire")
 ("JTAG_TMS_GLBL" "wire")
 ("JTAG_TRST_GLBL" "wire")
 ("JTAG_CAPTURE_GLBL" "reg")
 ("JTAG_RESET_GLBL" "reg")
 ("JTAG_SHIFT_GLBL" "reg")
 ("JTAG_UPDATE_GLBL" "reg")
 ("JTAG_RUNTEST_GLBL" "reg")
 ("JTAG_SEL1_GLBL" "reg")
 ("JTAG_SEL2_GLBL" "reg")
 ("JTAG_SEL3_GLBL" "reg")
 ("JTAG_SEL4_GLBL" "reg")
 ("JTAG_USER_TDO1_GLBL" "reg")
 ("JTAG_USER_TDO2_GLBL" "reg")
 ("JTAG_USER_TDO3_GLBL" "reg")
 ("JTAG_USER_TDO4_GLBL" "reg")
 ("glbl" "module_declaration"))
