(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Wen" "input logic")
 ("Oen" "input logic")
 ("Cs" "input logic")
 ("Address" "input logic [7:0]")
 ("DataIn" "input logic [7:0]")
 ("DataOut" "output logic [7:0]")
 ("mem" "logic [7:0] / [RAM_DEPTH]")
 ("gp_ram" "module_declaration"))
