(("pin1" "input wire [1:0]")
 ("pin2" "input wire")
 ("pin3" "input wire [1:0]")
 ("pin4" "input wire")
 ("pin5" "output wire")
 ("pin6" "output wire [10:0]")
 ("pin7" "output reg")
 ("pin8" "output reg [1:0]")
 ("testmodule" "module_declaration"))
