(("burst_drv" "typedef class")
 ("EXECUTING" "int")
 ("OBSERVED" "int")
 ("SUB_OBSERVED" "int")
 ("cfg" "protected burst_drv_cfg")
 ("reset_cfg" "local burst_drv_cfg")
 ("rx_factory" "protected burst_xn")
 ("reset_rx_factory" "local burst_xn")
 ("in_chan" "burst_xn_channel")
 ("obs_chan" "burst_xn_channel")
 ("tr_main" "burst_xn")
 ("c" "class_declaration")
 ("f" "function_body_declaration")
 ("t" "task_body_declaration")
 ("pv_t" "task_body_declaration")
 ("p_t" "task_body_declaration")
 ("v_t" "task_body_declaration")
 ("vp_t" "task_body_declaration")
 ("pv_t" "task_body_declaration")
 ("cfg" "burst_drv_cfg")
 ("rst_type" "reset_e")
 ("inst" "string")
 ("stream_id" "int")
 ("cfg" "burst_drv_cfg")
 ("in_chan" "burst_xn_channel")
 ("obs_chan" "burst_xn_channel")
 ("rx_factory" "burst_xn")
 ("new" "class_constructor_prototype")
 ("start" "task_body_declaration")
 ("start" "task_body_declaration")
 ("start" "task_body_declaration")
 ("burst_drv" "class_declaration"))
