(("attribute1" "rand int")
 ("attribute2" "rand logic [3:0]")
 ("a" "int")
 ("b" "logic [3:0]")
 ("new" "class_constructor_declaration")
 ("a" "input int")
 ("b" "input logic [3:0]")
 ("T1" "task_body_declaration")
 ("A" "class_declaration")
 ("foo" "package_declaration"))
