(("t" "module_declaration")
 ("f" "function_body_declaration")
 ("f" "function_body_declaration")
 ("a" "C")
 ("g" "function_body_declaration")
 ("C" "class_declaration")
 ("t" "task_body_declaration")
 ("f" "function_body_declaration")
 ("pure_virt_func_class" "class_declaration")
 ("my_vif_t" "virtual my_if")
 ("phase" "uvm_phase")
 ("start_of_simulation_phase" "function_body_declaration")
 ("base_test" "class_declaration"))
