(("req" "logic")
 ("gnt" "logic")
 ("addr" "logic [7:0]")
 ("data" "logic [7:0]")
 ("mode" "logic [1:0]")
 ("start" "logic")
 ("rdy" "logic")
 ("simple_bus" "interface_declaration")
 ("a" "simple_bus")
 ("clk" "input bit")
 ("avail" "logic")
 ("memMod" "module_declaration")
 ("b" "simple_bus")
 ("clk" "input bit")
 ("cpuMod" "module_declaration")
 ("clk" "logic")
 ("simple_bus" "module_instantiation")
 ("memMod" "module_instantiation")
 ("cpuMod" "module_instantiation")
 ("top" "module_declaration"))
