(("PARAMETER_0" "parameter_declaration")
 ("PARAMETER_1" "parameter_declaration")
 ("PARAMETER_2" "parameter_declaration")
 ("PARAMETER_3" "parameter_declaration")
 ("PARAMETER_4" "parameter_declaration")
 ("PARAMETER_5" "parameter_declaration")
 ("PARAM_6" "parameter_declaration")
 ("PARAMETER7" "parameter_declaration")
 ("PARAM_LONGER" "parameter_declaration")
 ("PARAM_EVEN_LONGER" "parameter_declaration")
 ("PARAMETER_10" "parameter_declaration")
 ("PARAMETER_11" "parameter_declaration")
 ("PARAMETER_12" "parameter_declaration")
 ("PARAMETER_13" "parameter_declaration")
 ("clk" "input logic")
 ("rst_n" "input logic")
 ("signal_1" "input logic")
 ("signal2" "input logic [PARAMETER_0-1:0]")
 ("signal_longer_name" "input logic [PARAMETER_1-1:0]")
 ("signal3" "input logic")
 ("signal_other_name" "output logic [PARAMETER_2-1:0]")
 ("another_signal" "input logic [PARAMETER_3-1:0]")
 ("even_more_signals" "output logic [PARAMETER_4-1:0]")
 ("output_signal" "output logic")
 ("more_output_signals" "output logic")
 ("packed_array" "input logic")
 ("unpacked_array" "input logic [4:0][3:0]")
 ("unpacked_array_2" "input logic [4:0]")
 ("name1" "logic")
 ("name2" "logic [1:0]")
 ("name_3" "logic")
 ("name_4" "logic")
 ("some_type_t" "struct packed{\nlogic name1;\nlogic [1:0] name2;\nlogic name_3;\nlogic name_4;\n}")
 ("param_port_list" "module_declaration")
 ("PARAMETER_0" "parameter_declaration")
 ("PARAMETER_11" "parameter_declaration")
 ("PARAMETER_222" "parameter_declaration")
 ("clk" "input logic")
 ("rst_n" "input logic")
 ("inputs" "input logic [3:0]")
 ("outputs" "output logic [15:0]")
 ("param_port_list" "module_declaration")
 ("val" "T1")
 ("val2" "T22")
 ("val3" "T333")
 ("parameterized_class" "class_declaration")
 ("val" "T1")
 ("val2" "T22")
 ("val3" "T333")
 ("parameterized_class2" "class_declaration"))
