(("clk" "input")
 ("rst_n" "input")
 ("req_soft_rst" "input")
 ("soft_rst_dne" "output")
 ("dma_halt" "output")
 ("tx_quiet" "input")
 ("rx_quiet" "input")
 ("soft_rst" "output")
 ("hs_async_rst_n" "output")
 ("state" "reg [1:0]")
 ("IDLE" "local_parameter_declaration")
 ("soft_rst" "module_declaration"))
