(("example_t" "class_declaration")
 ("example_t" "typedef class")
 ("max_len" "input bit [8:0]")
 ("mv" "input bit")
 ("algo_cfg" "ref example_t")
 ("orig_img" "ref bit [17:0] / []")
 ("cmp_img" "ref bit [15:0] / []")
 ("algo_cfg" "example_t")
 ("recmp_en" "input bit")
 ("re_pixel_output_tmp" "output bit [17:0]")
 ("cmp_core" "function_body_declaration")
 ("test" "class_declaration"))
