(("variable1" "logic")
 ("variable2" "logic signed [1:0]")
 ("variable3" "logic")
 ("variable4" "logic signed [1:0]")
 ("enum_t" "enum logic [1:0] {STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3}")
 ("enum_t" "enum logic [1:0] {STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum logic [1:0] {\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum logic [1:0] {\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3}")
 ("enum_t" "enum logic [1:0]\n{STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum logic [1:0]\n{\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum logic [1:0]\n{\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum {STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3}")
 ("enum_t" "enum {STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum {\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum {\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3}")
 ("enum_t" "enum\n{STATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum\n{\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("enum_t" "enum\n{\nSTATE_0,\nSTATE_1,\nSTATE_2,\nSTATE_3\n}")
 ("typedef_enum_indent" "module_declaration"))
