(("addr" "rand int unsigned")
 ("data" "rand int unsigned")
 ("delay" "rand int unsigned")
 ("name" "string")
 ("new" "class_constructor_declaration")
 ("simple_item" "class_declaration")
 ("str" "string")
 ("subdata" "mydata")
 ("field" "int")
 ("e1" "myenum")
 ("queue" "int [$]")
 ("mydata" "class_declaration")
 ("data" "rand bit [127:0] []")
 ("name" "string")
 ("sequencer" "uvm_sequencer_base")
 ("parent_seq" "uvm_sequence")
 ("new" "class_constructor_declaration")
 ("my_trans" "class_declaration")
 ("uvm" "module_declaration")
 ("tt" "module_declaration"))
