(("in1" "input logic [7:0]")
 ("in2" "input logic")
 ("type1" "custom_type")
 ("out" "output logic")
 ("type2" "custom_type")
 ("signal1" "logic [7:0]")
 ("signal2" "logic")
 ("type3" "custom_type")
 ("foo" "module_declaration"))
