(("str1" "input string")
 ("str1" "input string")
 ("str1" "input string")
 ("data" "input bit[7:0] / []")
 ("data" "output bit[7:0] / []")
 ("key_high_u" "int")
 ("key_low_u" "int")
 ("key_low_l" "int")
 ("iv_high_u" "int")
 ("iv_high_l" "int")
 ("iv_low_u" "int")
 ("iv_low_l" "int")
 ("skip" "int")
 ("a" "logic")
 ("testbench" "module_declaration"))
