(("log" "static vmm_log")
 ("log" "class_property")
 ("addr" "logic [31:0]")
 ("data" "logic [31:0]")
 ("mask" "logic [31:0]")
 ("op" "logic [31:0]")
 ("new" "class_constructor_declaration")
 ("mipsbfm_trans" "class_declaration")
 ("clk" "input")
 ("data" "logic [31:0]")
 ("addr" "logic [31:0]")
 ("mask" "logic [31:0]")
 ("op" "logic [31:0]")
 ("valid" "logic")
 ("mipsbfm_if" "interface_declaration")
 ("in_chan" "mipsbfm_trans_channel")
 ("in_chan" "class_property")
 ("mipsbfm_master" "class_declaration"))
