(("asdf" "module_declaration")
 ("atype" "rand AddrType")
 ("MyBus" "class_declaration")
 ("atype" "rand AddrType")
 ("MyBus" "class_declaration")
 ("atype" "rand AddrType")
 ("MyBus" "class_declaration")
 ("fool" "module_declaration")
 ("foo" "module_declaration")
 ("myclass" "class_declaration"))
