(("mbox" "mailbox")
 ("smtx" "semaphore")
 ("id" "int")
 ("Rx" "virtual Rx_if")
 ("mbox" "mailbox")
 ("id" "int")
 ("Rx" "virtual Rx_if.TB")
 ("new" "class_constructor_declaration")
 ("Driver" "class_declaration"))
