(("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("func1" "function_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("task1" "task_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("task1" "task_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("task1" "task_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("task1" "task_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("ref2" "ref bit [17:0]")
 ("ref3" "ref bit [15:0]")
 ("ex1" "example_t")
 ("in3" "input bit")
 ("out1" "output bit [17:0]")
 ("task1" "task_body_declaration")
 ("in1" "input bit [8:0]")
 ("in2" "input bit")
 ("ref1" "ref example_t")
 ("task1" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("func2" "function_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task2" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task2" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task2" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task2" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task2" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("func3" "function_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task3" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task3" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task3" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task3" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task3" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("func4" "function_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task4" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task4" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task4" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task4" "task_body_declaration")
 ("in" "input bit")
 ("out" "output bit [3:0]")
 ("task4" "task_body_declaration")
 ("test" "class_declaration"))
