(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Cs" "input logic")
 ("Wen" "input logic")
 ("Oen" "input logic")
 ("Address" "input logic [7:0]")
 ("DataIn" "input logic [7:0]")
 ("DataOut" "output logic [7:0]")
 ("Switches" "output logic [7:0]")
 ("Temp" "output logic [7:0]")
 ("last_mem_space" "enum logic {REGS, GP}")
 ("Cs_gp" "logic")
 ("Cs_regs" "logic")
 ("DataOut_gp" "logic [7:0]")
 ("DataOut_regs" "logic [7:0]")
 ("gp_ram" "module_instantiation")
 ("regs_ram" "module_instantiation")
 ("ram" "module_declaration"))
