(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("DMA_Bus_req" "input logic")
 ("DMA_Bus_grant" "input logic")
 ("DMA_Idle" "input logic")
 ("CPU_DataOut" "input logic [7:0]")
 ("DMA_DataOut" "input logic [7:0]")
 ("RAM_DataIn" "output logic [7:0]")
 ("CPU_Address" "input logic [7:0]")
 ("DMA_Address" "input logic [7:0]")
 ("RAM_Address" "output logic [7:0]")
 ("CPU_Cs" "input logic")
 ("DMA_Cs" "input logic")
 ("RAM_Cs" "output logic")
 ("CPU_Oen" "input logic")
 ("DMA_Oen" "input logic")
 ("RAM_Oen" "output logic")
 ("CPU_Wen" "input logic")
 ("DMA_Wen" "input logic")
 ("RAM_Wen" "output logic")
 ("state_t" "enum logic {GRANT_CPU, GRANT_DMA}")
 ("state" "state_t")
 ("ram_arbiter" "module_declaration"))
