(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Wen" "input logic")
 ("Oen" "input logic")
 ("Cs" "input logic")
 ("Address" "input logic [7:0]")
 ("DataIn" "input logic [7:0]")
 ("DataOut" "output logic [7:0]")
 ("Switches" "output logic [7:0]")
 ("Temp" "output logic [7:0]")
 ("DMA_RX_BUFFER_MSB_AUX" "logic [7:0]")
 ("DMA_RX_BUFFER_MID_AUX" "logic [7:0]")
 ("DMA_RX_BUFFER_LSB_AUX" "logic [7:0]")
 ("NEW_INST_AUX" "logic [7:0]")
 ("DMA_TX_BUFFER_MSB_AUX" "logic [7:0]")
 ("DMA_TX_BUFFER_LSB_AUX" "logic [7:0]")
 ("SWITCH_BASE_AUX" "logic [7:0]")
 ("SWITCH_BASE_AUX2" "logic [7:0]")
 ("SWITCH_BASE_AUX3" "logic [7:0]")
 ("SWITCH_BASE_AUX4" "logic [7:0]")
 ("SWITCH_BASE_AUX5" "logic [7:0]")
 ("SWITCH_BASE_AUX6" "logic [7:0]")
 ("SWITCH_BASE_AUX7" "logic [7:0]")
 ("SWITCH_BASE_AUX8" "logic [7:0]")
 ("LEVER_BASE_AUX" "logic [7:0]")
 ("LEVER_BASE_AUX2" "logic [7:0]")
 ("LEVER_BASE_AUX3" "logic [7:0]")
 ("LEVER_BASE_AUX4" "logic [7:0]")
 ("LEVER_BASE_AUX5" "logic [7:0]")
 ("LEVER_BASE_AUX6" "logic [7:0]")
 ("LEVER_BASE_AUX7" "logic [7:0]")
 ("LEVER_BASE_AUX8" "logic [7:0]")
 ("LEVER_BASE_AUX9" "logic [7:0]")
 ("LEVER_BASE_AUX10" "logic [7:0]")
 ("CAL_OP_AUX" "logic [7:0]")
 ("T_STAT_AUX" "logic [7:0]")
 ("BIN2BCD_PERIOD" "local_parameter_declaration")
 ("bin2bcd_cnt" "logic [31:0]")
 ("bin2bcd_done" "logic")
 ("bin2bcd_temp" "logic [7:0]")
 ("bin2bcd_start" "logic")
 ("bin2bcd" "module_instantiation")
 ("regs_ram" "module_declaration"))
