(("CLKT" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("InData" "logic [7:0]")
 ("OutData" "logic [7:0]")
 ("FlagC" "logic")
 ("FlagE" "logic")
 ("FlagN" "logic")
 ("FlagZ" "logic")
 ("ALU_op" "alu_op")
 ("alu" "module_instantiation")
 ("reset_system" "task_body_declaration")
 ("inst" "input alu_op")
 ("DATA" "input logic[7:0]")
 ("CYCLES" "local_parameter_declaration")
 ("execute_instruction" "task_body_declaration")
 ("D" "input logic [7:0]")
 ("op" "input alu_op")
 ("op_one_operand" "task_body_declaration")
 ("A" "input logic [7:0]")
 ("B" "input logic [7:0]")
 ("op" "input alu_op")
 ("op_two_operands" "task_body_declaration")
 ("sumA" "input logic [7:0]")
 ("sumB" "input logic [7:0]")
 ("do_add" "task_body_declaration")
 ("subA" "input logic [7:0]")
 ("subB" "input logic [7:0]")
 ("do_sub" "task_body_declaration")
 ("andA" "input logic [7:0]")
 ("andB" "input logic [7:0]")
 ("do_and" "task_body_declaration")
 ("orA" "input logic [7:0]")
 ("orB" "input logic [7:0]")
 ("do_or" "task_body_declaration")
 ("xorA" "input logic [7:0]")
 ("xorB" "input logic [7:0]")
 ("do_xor" "task_body_declaration")
 ("tb_alu" "module_declaration"))
