(("CLKT" "local_parameter_declaration")
 ("BIN_WIDTH" "local_parameter_declaration")
 ("DEC_DIGITS" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("DataBin" "logic [BIN_WIDTH-1:0]")
 ("Start" "logic")
 ("DataBCD" "logic [DEC_DIGITS*4-1:0]")
 ("Done" "logic")
 ("bin2bcd" "module_instantiation")
 ("reset_system" "task_body_declaration")
 ("data" "input logic [BIN_WIDTH-1:0]")
 ("convert_binary2bcd" "task_body_declaration")
 ("tb_bin2bcd" "module_declaration"))
