(("CLKT" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("ROM_Data" "logic [11:0]")
 ("DataIn" "logic [7:0]")
 ("ALU_DataOut" "logic [7:0]")
 ("DMA_Ready" "logic")
 ("DMA_Req" "logic")
 ("FlagC" "logic")
 ("FlagE" "logic")
 ("FlagN" "logic")
 ("FlagZ" "logic")
 ("ALU_op" "alu_op")
 ("DMA_Ack" "logic")
 ("DMA_Tx_Start" "logic")
 ("Databus" "logic [7:0]")
 ("RAM_Addr" "logic [7:0]")
 ("RAM_Cs" "logic")
 ("RAM_Oen" "logic")
 ("RAM_Wen" "logic")
 ("ROM_Addr" "logic [11:0]")
 ("ALU_DataIn" "logic [7:0]")
 ("DataOut" "logic [7:0]")
 ("cpu" "module_instantiation")
 ("ROM" "logic [11:0] [4096]")
 ("init_rom" "task_body_declaration")
 ("reset_system" "task_body_declaration")
 ("dma_req" "task_body_declaration")
 ("tb_cpu" "module_declaration"))
