(("CLKT" "local_parameter_declaration")
 ("FREQ_CLK" "local_parameter_declaration")
 ("TX_SPEED" "local_parameter_declaration")
 ("BIT_CYCLES" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("RX_Empty" "wire")
 ("RX_Full" "wire")
 ("RX_Data" "wire [7:0]")
 ("Bus_grant" "logic")
 ("Dma_Tx_Start" "logic")
 ("RXD" "logic")
 ("DataIn" "logic [7:0]")
 ("TXD" "logic")
 ("TX_Ready" "logic")
 ("Address" "logic [7:0]")
 ("Bus_req" "logic")
 ("Cs" "logic")
 ("Data_Read" "logic")
 ("DataOut" "logic [7:0]")
 ("Dma_Tx_Ready" "logic")
 ("Oen" "logic")
 ("TX_Data" "logic [7:0]")
 ("TX_Valid" "logic")
 ("Wen" "logic")
 ("dma" "module_instantiation")
 ("uart" "module_instantiation")
 ("reset_system" "task_body_declaration")
 ("Data" "input logic [7:0]")
 ("serial_rx" "task_body_declaration")
 ("receive_1byte" "task_body_declaration")
 ("receive_2bytes" "task_body_declaration")
 ("receive_3bytes" "task_body_declaration")
 ("rx_dma" "task_body_declaration")
 ("start_tx_dma" "task_body_declaration")
 ("get_databus" "task_body_declaration")
 ("wait_msb_send_lsb" "task_body_declaration")
 ("tx_dma" "task_body_declaration")
 ("tb_dma" "module_declaration"))
