(("Clk" "input logic")
 ("Rst_n" "output logic")
 ("RXD" "output logic")
 ("TXD" "input logic")
 ("Temp" "input logic [7:0]")
 ("Switches" "input logic [7:0]")
 ("ROM_Data" "output logic [11:0]")
 ("ROM_Addr" "input logic [11:0]")
 ("FREQ_CLK" "local_parameter_declaration")
 ("TX_SPEED" "local_parameter_declaration")
 ("BIT_CYCLES" "local_parameter_declaration")
 ("ROM" "logic [11:0] [4096]")
 ("init_rom" "task_body_declaration")
 ("init_values" "task_body_declaration")
 ("reset_system" "task_body_declaration")
 ("Data" "input logic [7:0]")
 ("serial_rx" "task_body_declaration")
 ("tb_program" "module_declaration"))
