(("CLKT" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("Address" "logic [7:0]")
 ("Cs" "logic")
 ("DataIn" "logic [7:0]")
 ("Oen" "logic")
 ("Wen" "logic")
 ("DataOut" "logic [7:0]")
 ("Switches" "logic [7:0]")
 ("Temp" "logic [7:0]")
 ("ram" "module_instantiation")
 ("reset_system" "task_body_declaration")
 ("addr" "input logic [7:0]")
 ("data" "input logic [7:0]")
 ("write_ram" "task_body_declaration")
 ("addr" "input logic [7:0]")
 ("read_ram" "task_body_declaration")
 ("test_regs" "task_body_declaration")
 ("test_gp" "task_body_declaration")
 ("tempdata" "logic [7:0]")
 ("tb_ram" "module_declaration"))
