(("Clk" "logic")
 ("Rst_n" "logic")
 ("RXD" "logic")
 ("TXD" "logic")
 ("Temp" "logic [7:0]")
 ("Switches" "logic [7:0]")
 ("ROM_Data" "logic [11:0]")
 ("ROM_Addr" "logic [11:0]")
 ("tb_clocks" "module_instantiation")
 ("tb_program" "module_instantiation")
 ("ucontroller" "module_instantiation")
 ("tb_top" "module_declaration"))
