(("CLKT" "local_parameter_declaration")
 ("FREQ_CLK" "local_parameter_declaration")
 ("TX_SPEED" "local_parameter_declaration")
 ("BIT_CYCLES" "local_parameter_declaration")
 ("Clk" "logic")
 ("Rst_n" "logic")
 ("Data_Read" "logic")
 ("RXD" "logic")
 ("TX_DataIn" "logic [7:0]")
 ("TX_Valid" "logic")
 ("Data_Out" "logic [7:0]")
 ("Empty" "logic")
 ("Full" "logic")
 ("TXD" "logic")
 ("TX_Ready" "logic")
 ("uart" "module_instantiation")
 ("reset_system" "task_body_declaration")
 ("Data" "input logic [7:0]")
 ("serial_rx" "task_body_declaration")
 ("Data" "input logic [7:0]")
 ("serial_tx" "task_body_declaration")
 ("read_from_fifo" "task_body_declaration")
 ("tb_uart" "module_declaration"))
