(("FREQ_CLK" "parameter_declaration")
 ("TX_SPEED" "parameter_declaration")
 ("Clk" "input logic")
 ("Rst_n" "input logic")
 ("TX_Valid" "input logic")
 ("TX_Ready" "output logic")
 ("TX_DataIn" "input logic [7:0]")
 ("TXD" "output logic")
 ("RXD" "input logic")
 ("Data_Read" "input logic")
 ("Data_Out" "output logic [7:0]")
 ("Full" "output logic")
 ("Empty" "output logic")
 ("TX_Ready_i" "logic")
 ("TX_Start" "logic")
 ("RX_Valid" "logic")
 ("Fifo_In" "logic [7:0]")
 ("Fifo_Wren" "logic")
 ("uart_tx" "module_instantiation")
 ("uart_rx" "module_instantiation")
 ("sreg" "module_instantiation")
 ("fifo_wrapper" "module_instantiation")
 ("uart" "module_declaration"))
