(("FREQ_CLK" "parameter_declaration")
 ("TX_SPEED" "parameter_declaration")
 ("Clk" "input logic")
 ("Rst_n" "input logic")
 ("Start" "input logic")
 ("Data" "input logic [7:0]")
 ("EOT" "output logic")
 ("TXD" "output logic")
 ("PULSE_END_OF_COUNT" "local_parameter_declaration")
 ("state_t" "enum logic[1:0] {\n                 IDLE = 0,\n                 START_BIT = 1,\n                 SEND_DATA = 2,\n                 STOP_BIT = 3\n                 }")
 ("state" "state_t")
 ("next_state" "state_t")
 ("load_data" "logic")
 ("data_reg" "logic [7:0]")
 ("bit_end" "logic")
 ("data_send_end" "logic")
 ("bit_ctr_ena" "logic")
 ("period_cnt" "logic [31:0]")
 ("bit_cnt" "logic [31:0]")
 ("uart_tx" "module_declaration"))
