(("Clk" "input logic")
 ("Rst_n" "input logic")
 ("RXD" "input logic")
 ("TXD" "output logic")
 ("ROM_Data" "input logic [11:0]")
 ("ROM_Addr" "output logic [11:0]")
 ("Temp" "output logic [7:0]")
 ("Switches" "output logic [7:0]")
 ("DMA_Oen" "logic")
 ("asdf_e" "enum   {ASD, ASDF2}")
 ("DMA_Wen" "logic")
 ("DMA_Cs" "logic")
 ("CPU_Oen" "logic")
 ("CPU_Wen" "logic")
 ("CPU_Cs" "logic")
 ("CPU_Address" "logic [7:0]")
 ("DMA_Address" "logic [7:0]")
 ("DMA_DataOut" "logic [7:0]")
 ("CPU_DataOut" "logic [7:0]")
 ("Dma_Idle" "logic")
 ("TX_Data" "logic [7:0]")
 ("TX_Ready" "logic")
 ("TX_Valid" "logic")
 ("Data_Read" "logic")
 ("RX_Data" "logic [7:0]")
 ("RX_Empty" "logic")
 ("RX_Full" "logic")
 ("RAM_DataOut" "logic [7:0]")
 ("RAM_DataIn" "logic [7:0]")
 ("ALU_DataIn" "logic [7:0]")
 ("ALU_DataOut" "logic [7:0]")
 ("ALU_op" "alu_op")
 ("FlagE" "logic")
 ("FlagN" "logic")
 ("FlagC" "logic")
 ("FlagZ" "logic")
 ("RAM_Address" "logic [7:0]")
 ("RAM_Wen" "logic")
 ("RAM_Oen" "logic")
 ("RAM_Cs" "logic")
 ("Bus_grant" "logic")
 ("Bus_req" "logic")
 ("Dma_Tx_Ready" "logic")
 ("Dma_Tx_Start" "logic")
 ("cpu" "module_instantiation")
 ("alu" "module_instantiation")
 ("dma" "module_instantiation")
 ("uart" "module_instantiation")
 ("ram_arbiter" "module_instantiation")
 ("ram" "module_instantiation")
 ("ucontroller" "module_declaration"))
