(("Always"
  ("slv_aw_ready" . #<marker at 10347 in axi_demux.sv>)
  ("slv_ar_ready" . #<marker at 18935 in axi_demux.sv>)
  ("mst_reqs_o" . #<marker at 24304 in axi_demux.sv>)
  ("push_en" . #<marker at 30675 in axi_demux.sv>))
 ("Initial"
  ("validate_params" . #<marker at 25896 in axi_demux.sv>))
 ("Instance"
  ("spill_register" . #<marker at 3693 in axi_demux.sv>)
  ("spill_register" . #<marker at 4165 in axi_demux.sv>)
  ("spill_register" . #<marker at 4626 in axi_demux.sv>)
  ("spill_register" . #<marker at 5081 in axi_demux.sv>)
  ("spill_register" . #<marker at 5553 in axi_demux.sv>)
  ("spill_register" . #<marker at 9167 in axi_demux.sv>)
  ("spill_register" . #<marker at 9672 in axi_demux.sv>)
  ("axi_demux_id_counters" . #<marker at 13917 in axi_demux.sv>)
  ("counter" . #<marker at 15379 in axi_demux.sv>)
  ("spill_register" . #<marker at 16160 in axi_demux.sv>)
  ("spill_register" . #<marker at 16718 in axi_demux.sv>)
  ("rr_arb_tree" . #<marker at 17186 in axi_demux.sv>)
  ("spill_register" . #<marker at 17883 in axi_demux.sv>)
  ("spill_register" . #<marker at 18328 in axi_demux.sv>)
  ("axi_demux_id_counters" . #<marker at 21525 in axi_demux.sv>)
  ("spill_register" . #<marker at 23007 in axi_demux.sv>)
  ("rr_arb_tree" . #<marker at 23475 in axi_demux.sv>)
  ("delta_counter" . #<marker at 31768 in axi_demux.sv>)
  ("axi_demux" . #<marker at 35420 in axi_demux.sv>)))
